### ISSUE TITLE
[URGENT] Highlight the no. of profiles and external account on airdrop page

### ISSUE THREAD

**Issue by kanniec826** [desmos-labs/website#43]
Suggested to show the number of created profiles and connected external accounts for user to reference on.

Below is the design Rooty created:
https://www.figma.com/proto/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?page-id=298%3A459&node-id=1833%3A23077&viewport=241%2C48%2C0.43&scaling=min-zoom&starting-point-node-id=624%3A4083

@rachelhox Please help to do this story first, thanks a lot

 @Rooty2020 Please note

**Comment by Rooty2020** [comment]
https://www.figma.com/file/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?node-id=1915%3A26139

**Comment by nicoletting** [comment]
Several [feedback](https://www.reddit.com/r/DesmosNetwork/comments/rs3aty/desmos_main_website_is_lacking_key_information/) from user @rachelhox please update 🙇🏻‍♀️
![image](https://user-images.githubusercontent.com/90247802/148012322-fed38e03-4d27-4edd-8bb7-d29fe4ff529e.png)
