### ISSUE TITLE
[URGENT] Add "download App" to the Desmos Profile section

### ISSUE THREAD

**Issue by Rooty2020** [desmos-labs/website#44]
<img width="630" alt="Screenshot 2022-01-04 at 1 43 42 PM" src="https://user-images.githubusercontent.com/60619414/148014724-bdf4328e-1e9a-4199-a2a0-c70ed74f6ce6.png">

**Comment by nicoletting** [comment]
Several [feedback](https://www.reddit.com/r/DesmosNetwork/comments/rs3aty/desmos_main_website_is_lacking_key_information/) from user
