### ISSUE TITLE
[URGENT] add the airdrop banner and verifier quick link

### ISSUE THREAD

**Issue by nicoletting** [desmos-labs/website#47]
Add the **quick link** with the **banner** below, 
also the user can close the overlay layer with **close button**🙇🏻‍♀️
@rachelhox 
![image](https://user-images.githubusercontent.com/90247802/148018040-662c1e9e-9358-4fa4-adb3-d5adec82f919.png)

figma file:
https://www.figma.com/proto/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?page-id=298%3A459&node-id=629%3A5998&viewport=287%2C48%2C0.5&scaling=min-zoom&starting-point-node-id=624%3A4083

**Comment by rachelhox** [comment]
closed with PR #70 :)
