### ISSUE TITLE
Broken/wrong GitHub links

### ISSUE THREAD

**Issue by RiccardoM** [desmos-labs/website#6]
Under the "Join Desmos" section, the "ecosystem" word redirects to https://github.com/desmos-lab/desmos instead of https://github.com/desmos-labs/desmos (note the missing "s" at the end of "labs"). 

Also, I think that all the GitHub related links should redirect all to the same page, instead of three different places. 
Currently we have "ecosystem" which is broken, then the "Contribute the ecosystem" which redirects to https://github.com/desmos-labs/desmos and then the GitHub icon at the end of the page which redirects to https://github.com/desmos-labs. 

I think it might be better to redirect everything to https://github.com/desmos-labs

**Comment by kwunyeung** [comment]
Fixed in the latest update.
