### ISSUE TITLE
[URGENT] Grants Program

### ISSUE THREAD

**Issue by kanniec826** [desmos-labs/website#74]
Update on desmos website according to below prototype

https://www.figma.com/file/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?node-id=2723%3A39432

**Comment by kanniec826** [comment]
@nicoletting Please let us know when the UI is ready to deploy

**Comment by nicoletting** [comment]
both [desktop](https://www.figma.com/file/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?node-id=298%3A459) & [responsive](https://www.figma.com/file/lgF08ZQovUxkcCpEBDe47S/Desmos-Website-1.0.-%23ED6C53?node-id=710%3A32845) UI are ready
-> [Download materials here](https://drive.google.com/drive/u/1/folders/1Jg90Ag0rApE2X0KQB5A6vIHXrMeyl3in)

**Comment by kanniec826** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Issue-61d56716a7505500117ec7f1/issues/desmos-labs/desmos-website/74?planning-poker) with ZenHub @rachelhox

**Comment by kanniec826** [comment]
Updated. 
https://desmos.network/grants

**Comment by rachelhox** [comment]
Done!
