### ISSUE TITLE
Deploy footer issue #53

### ISSUE THREAD

**Issue by kanniec826** [desmos-labs/website#75]
Deploy footer Issue #53
[@rachelhox](https://github.com/rachelhox) Please deploy below,
https://app.zenhub.com/workspaces/issue-61d56716a7505500117ec7f1/issues/desmos-labs/desmos-website/53

Thanks.
[@nicoletting](https://github.com/nicoletting) Please note.

**Comment by kanniec826** [comment]
From @nicoletting 

![image.png](https://images.zenhubusercontent.com/61398a4b43495e5a84ddd98a/d62f9dbf-8edb-475f-b3de-e1effd82d8ac)
updated 2 linking for official telegram and youtube channel🙇🏻‍♀️

**Comment by rachelhox** [comment]
PR #76
